### ISSUE TITLE
Magic & Stone of Magic/Power

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#255]
Trying to use spells which require Stone of Magic or Stone of Power, but saying "lack of catalyst".  I've got magic gems and white stones.  Do I need something else?

**Comment by zajako** [comment]
Which spell are you using?  There was a bug before that was preventing mgems from use due to an icon issue. I built some code to auto swap the icon, based on your level. (Lineage changed it so mgems were required for low level and special new mgems were required for higher levels). My hack overwrode this so it shouldn't be an issue anymore.  Let me know what spells you're trying to cast and I can look into what is going on.

**Comment by AeacosL15** [comment]
I've tiered up, so can't retest them with a reaper.  I do remember having/trying invisibility and cancel though while having both magic gems and white stones in my inventory.

I'll try to catch Injection (reaper) online, he may have some spells we can test.
