### ISSUE TITLE
Hit/Stun Animation & Swing Delay

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#267]
Switched back to play a little live server and noticed I was not getting the hit animation nearly as much as I am on test.  On live I can stand in the middle of a group getting hit and would not get stun locked ... I would rarely got the "you were hit" animation unless I took damage or was hit with a spell.  On test it seems like every miss and 0 damage hit gives me the "you were hit" animation which prevents you from attacking or adds a short delay in between swings if you're already attacking.  In other words it's very easy to end up stun locked on test.

The other thing I noticed was since the swing speed fix, it takes a second from the time I left click until I actually attack.  On live I can spam the left mouse button and get hits in eventually killing the mob even if stunned.  On test, the combination of the attack delay and constantly being hit (even misses/0 dmg hits) make it very difficult to hunt even simple areas if you're being attacked from all sides (ant caves, lower floors of TOI, etc).

**Comment by AeacosL15** [comment]
Just noticed on the Stats tab of the character screen that it's showing -123 DG (melee evasion rating).  Not sure if that has something to do with the stun lock part of the issue.

**Comment by zajako** [comment]
Part of this is because of your DR, Level and Tier on the live server. Another part is, I fixed a bug that live server has. 

On live server it was intended to cap hit-rate at 95% and miss rate at 5%.  Meaning there was always a chance of being hit.  Also your DR on the test server likely doesn't reduce damage to 0 as often causing a sure miss.

Anyways, I'm not classifying this as a bug as of now, however if it turns out to be a problem making zones  un-huntable for high tier characters and such, I may revise the decision and change it away from this.
