### ISSUE TITLE
Can't place items in storage

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#295]
I've tried numerous items, but they aren't moved from my inventory to storage

**Comment by zajako** [comment]
I've narrowed this bug down, not sure how it got back in, because I did fix this before... I still need to debug it and figure it out again though.

I did verify that removing from warehouses works fine, however if you have no items in the warehouse it displays an error in the server stream, I'll fix that and make it send a message to the player while I'm at it.

**Comment by zajako** [comment]
this is now fixed. the issue was due to server version changes.
