### ISSUE TITLE
Cant move or attack if more than 5 monster hitting u

### ISSUE THREAD

**Issue by Capwne** [zajako/LineageHD#309]
Cant move or attack if more than 5 monster hitting u. Cant hunt if there are a lot monster on you.

**Comment by zajako** [comment]
This should be fixed on test server, please try it and let me know.

**Comment by Capwne** [comment]
I tried warp 6 orcs. if more than 5 orcs hitting on me. my char was constantly doing taking hit movement so cant move or attack. I think I need like a right + left click to force my char to attack monster instead of clicking left like crazy

**Comment by zajako** [comment]
were you on the test server or the live server? Live server still being HD.

**Comment by Capwne** [comment]
Test server.

**Comment by zajako** [comment]
Okay, thanks.

Right Click, Left Click was a Chinese server hack. to make it auto attack. You don't need that here, because if you double click an enemy and hold for a second it will auto attack.

You can use right click to make it easier to target the monster as well.


Also keep in mind, on test server, your DR RES etc are much lower, so you are flinching a lot because they are hitting you for enough damage to cause a flinch.

**Comment by zajako** [comment]
Try on live now.
