### ISSUE TITLE
Inventory 

### ISSUE THREAD

**Issue by Emberglin** [zajako/LineageHD#326]
Inventory mixes up on every restart, crash, character change, log out,...basicly inventory NEVER stays unjumbled. VERY, VERY time consuming before every log in, almost makes game unplayable.

**Comment by zajako** [comment]
Sorry about this.

This isn't a bug with the game, its me clearing your character configs. To help prevent a bug that is keeping some people from logging in.

I highly recommend waiting till I get character config stable and the crash bug fixed before spending time organizing the items again.

The bug is causing people to not be able to login, so to be safe i've been clearing them all when implementing fixes for them.
