### ISSUE TITLE
Elven Magic

### ISSUE THREAD

**Issue by Emberglin** [zajako/LineageHD#345]
There is an unknown catalist that is needed for elven magic, not the usual spirit or magic gems, something unknown and different. Maguc cannot be used, this needs fixing.

**Comment by zajako** [comment]
Yes, it does. I'm going to try to figure it out.

I've figured out the general issue, but its tricky. So the new client has 2 types of mgems and spirit gems.
One for when you're over level 70 and one for when you're under level 70.

Sadly the client is determing what is required to cast the spell instead of letting the server handle that. I've tricked it to work for under level 70, I thought I had gotten it to work for over level 70 too, but it doesn't seem to work anymore.

I'm gonna tweak it until I get it right.

**Comment by zajako** [comment]
This is fixed, closing the ticket.
