### ISSUE TITLE
Flinching from mobs

### ISSUE THREAD

**Issue by TheNorthernerUkyo** [zajako/LineageHD#383]
mobs that do 0 dmg still cause toon to flinch. This seems to only be from tiered mobs

**Comment by zajako** [comment]
This is because tiered mobs have their damage being absorbed by RES, which is outside of the scope of the damage check.  This means they are actually hitting you, but your RES is preventing damage.


I Moved the damage reduction for RES to be within this window, so it should prevent flinching in the future when RES prevents the damage.
