### ISSUE TITLE
donations

### ISSUE THREAD

**Issue by jojoscott** [zajako/LineageHD#475]
Hello Zajako .. i have made 1 donations of 50$ that came up to 70$ my currency that one i did receive .... But then i made another one for 20$ that came up to 28$ my currency but i never received that one... can you please check it out .. thank you i am Miyako in game and account is Naokia thanks again hope to hear soon

**Comment by zajako** [comment]
Hello, 
I see that your $20 donation did come through, but because it wasn't for a bundle, it was sent directly to your character "Naokia". Please check that character's inventory to see if it is there. When making a donation via the calculator you use your character's name that you'd like to receive the gifts on.

Also for issues about donations in the future, if possible please send a private message to me on discord, @zajako

Thanks!
